POST http://localhost:5000/syntaxTree/compileFile
Content-Type: application/x-www-form-urlencoded
Accept: application/json

FilePath=missing.cs&FileText=using+System.Unknown%3B+class+Program+%7Bpublic+void+F%28%29+%7B%7D%7D

> {%
if(response.body.Id) {
    client.global.set("nodeId", response.body.Id);
}
%}

###

POST http://localhost:5000/syntaxTree/getNodeInfo
Content-Type: application/x-www-form-urlencoded
Accept: application/json

NodeId={{nodeId}}

###

POST http://localhost:5000/syntaxTree/findNode
Content-Type: application/x-www-form-urlencoded
Accept: application/json

Start=14&End=17

###

POST http://localhost:5000/syntaxTree/resetActiveFile
Content-Type: application/x-www-form-urlencoded
Accept: application/json

###

POST http://localhost:5000/syntaxTree/ping
Content-Type: application/x-www-form-urlencoded
Accept: application/json
