POST http://localhost:5000/syntaxTree/setActiveFile
Content-Type: application/x-www-form-urlencoded
Accept: application/json

FilePath=Startup.cs

###

POST http://localhost:5000/syntaxTree/resetActiveFile
Content-Type: application/x-www-form-urlencoded
Accept: application/json

###

POST http://localhost:5000/syntaxTree/ping
Content-Type: application/x-www-form-urlencoded
Accept: application/json
